### PR TITLE
Updated default API version to current

### PR DESCRIPTION
**Pull request by stjeanp**
The default API version, 2013-06-01, has been retired. I've changed the default to 2015-05-01, which is the most current release.

More info:

http://support.theenterprisecloud.com/kb/default.asp?id=533&

### CODE REVIEW

**Comment by plribeiro3000** [comment]
@stjeanp Should we do a release candidate with this change?

**Comment by stjeanp** [comment]
Well... I'm working on SSH key management today, specifically adding support to create, edit, and delete keys. It's needed for the project I'm working on. There will probably be more features like that, but that's the current pain point. Do you want to hold off until that's in place?

Also, I started writing some shindo tests for authentication. They're not mock tests, but are live, using the spec interface that the eCloud API provides, so no actual cloud instances are touched. I've got the basic authentication tests done, testing both basic and API key authentication as well as valid, invalid, and missing/incomplete credentials. I am tagging those tests with the 'spec' tag, and have modified the Rakefile to add a test:spec operation as well as a filter for the test:travis operation so that it doesn't run the tests tagged with 'spec'.

That'll give us the ability to hit the real API and get real responses back, which has caught some issues that I've submitted pull requests for.

I haven't submitted a pull request for that, but can if you'd like to include it. Which also may or may not need to be included in the next release...

**Comment by plribeiro3000** [comment]
Yeah. Sent a PR for it so we can start discussing. =)

**Comment by stjeanp** [comment]
I think, with the inclusion of the ssh key functionality, that it's a good time to bump the version and release a new gem.

Thoughts?

**Comment by plribeiro3000** [comment]
@stjeanp Agreed. Do you want me to include this change?

**Comment by stjeanp** [comment]
I just closed this one and created a new pull request with this change and the gem version bumped. Sorry, I realized that I should have bumped that instead of making you do it too.

**Comment by plribeiro3000** [comment]
@stjeanp I'm ok doing the bump myself before releasing. =)

**Pull request closed without merging**
