### PR TITLE
Version 0.1.4

### PR DESCRIPTION
**Pull request by stjeanp**
I think it's time for a new release so that we can get the ssh key management functionality out there. I've replaced the API version with the current one and bumped the gem version.

### CODE REVIEW

**Comment by plribeiro3000** [comment]
Hmmm. Since there is a new feature i believe the right version would be `0.2.0`. Can you change that please?

**Comment by stjeanp** [comment]
Sure. I'll change that right now.

**Comment by plribeiro3000** [comment]
Awesome. Thanks!

**Comment by stjeanp** [comment]
All set, and the build and tests all passed. Looks like we're good to go...

**Comment by plribeiro3000** [comment]
Version `0.2.0` is out. =)

**Pull request merged**
